<?php include_once __DIR__.'/../components/header.php'; ?>

<main class="reglamento">
    <h3 class="reglamento__subtitulo">Introducción y definiciones</h3>
    <p class="reglamento__parrafo">Todos los usuarios deben estar de acuerdo con las siguientes condiciones de uso de la plataforma de membresías. Descripción del Sitio Web: K’TA Institute es una plataforma online de conexión entre usuarios que cuenta con una serie de herramientas de interacción, con la finalidad de distribuir contenido de carácter educativo y también de recibimiento de pagos de los mismos. Tipos de usuario: Distinguimos dos tipos principales de usuarios del Sitio Web (Tutores y Estudiantes)</p>
    <p class="reglamento__parrafo">Usuario egresado (“Estudiante”): es quien busca en el Sitio Web ayuda académica, para lo cual desea utilizar las herramientas disponibles en el (b) Usuario profesor (“Tutor””). Se refiere a una persona conocedora y capacitada de una o varias materias(s) específica(s), quien, a través de la Plataforma estudiantes, imparte a los estudiantes su conocimiento a través de los diferentes formatos que provee la plataforma, los cuales pueden ser contenido escrito publicado como un artículo, vídeos instruccionales o cursos que incluye un conjunto de herramientas educacionales (vídeos, publicaciones, actividades interactivas, evaluaciones, foros, entre otros).</p>
    <p class="reglamento__parrafo">Estos Términos y Condiciones de Servicio (los “Términos y Condiciones”) constituyen un contrato entre el usuario (Usted), en su calidad de usuario y K’TA Institute en todo lo referente al uso del Sitio Web y la contratación de los servicios que se prestan a través de este. Cuando usted utiliza el sitio web, usted reconoce y declara que ha leído y comprendido estos términos y condiciones, obligándose a cumplir, sin reservas, las estipulaciones contenidas en ellos. En consecuencia, todo usuario del sitio web debe leer atentamente estos términos y condiciones, revisándolos periódicamente ante eventuales actualizaciones. El Sitio Web pone a disposición de sus estudiantes una plataforma tecnológica de conexión. El objeto de K’TA Institute es ayudar a conectar en línea a estudiantes y profesores (esto es, quienes interactúan con los estudiantes en el Sitio Web con el objeto de impartir clases, información y conocimiento online, para que estos últimos impartan clases a través de nuestra interfaz conforme a lo solicitado por los estudiantes.</p>
    <p class="reglamento__parrafo">Nuestros Servicios permiten a los estudiantes ponerse en contacto con profesores quienes imparten clases grabadas y en directo, prestando servicios de educación y tutoría (membresía extendida) por medio de Nuestros Servicios, los cuales incluyen, entre otros recursos, debates y foros de tópicos tasación, gestión y administración de empresas, representación y solución de conflictos ante el IRS, declaración de impuestos individuales y empresas, seguros de salud y vida, procesos de inmigración y otros temas de valor para los inmigrantes de habla hispana residentes legales o no en el territorio de los Estados Unidos permitiendo la interacción entre los usuarios.</p>
    <p class="reglamento__parrafo">El rol de K’TA Institute a través de su plataforma es poner a disposición del Sitio Web, las herramientas de interacción disponibles en éste. Del mismo modo, K’TA Institute, no es un agente de contratación o representante de los estudiantes. La plataforma o sitio web no permiten el acceso a personas residentes en países extranjeros a los temas de impuestos y inmigración.</p>

    <h3 class="reglamento__subtitulo">Objeto</h3>
    <p class="reglamento__parrafo">A través del Sitio Web K’TA Institute otorga a los estudiantes acceso a diversos contenidos y herramientas interactivas, con el fin de facilitar la distribución de contenidos y ejercicio de tutorías (conversatorio, debates) educativos con el apoyo de Profesores (en adelante, Tutor). K’TA Institute se reserva el derecho de realizar modificaciones a estos Términos y Condiciones en cualquier momento, lo que será debidamente informado a los estudiantes a través del Sitio Web. El estudiante reconoce y acepta que el uso del Sitio Web, de los Servicios y de las herramientas interactivas son de su única y exclusiva responsabilidad de K’TA Instituto. La plataforma y el Sitio Web está restringido para las personas residentes en cualquier país extranjero a el territorio estadounidense en cursos e informaciones referentes a impuestos y inmigración de los EE.UU..</p>
    
    <h3 class="reglamento__subtitulo">Servicios</h3>
    <p class="reglamento__parrafo">Los Servicios ofrecidos a través del Sitio Web y plataforma son clases online en vivo y grabadas, con una membresía extendida de acuerdo con los niveles de enseñanza que el estudiante se haya registrado.</p>

    <h3 class="reglamento__subtitulo">Condiciones de acceso y uso del sitio</h3>
    <p class="reglamento__parrafo">Los estudiantes que deseen contratar los Servicios deberán registrarse en el Sitio Web, completando un formulario que contiene datos tales como: nombre completo, dirección de habitación, número de teléfono, correo electrónico, entre otros. La aceptación de estos Términos y Condiciones incluye la aceptación de nuestras políticas de seguridad. Los estudiantes aceptan que la información que proporcionen a K’TA Institute, ya sea en el proceso de registro o en cualquier otro momento que sea requerida, deberá ser verdadera, precisa, actualizada y completa, asumiendo la obligación de mantener dicha información actualizada en todo momento. El estudiante es el único responsable de mantener la confidencialidad de su clave de acceso y de restringir el acceso al equipo o dispositivo por medio del cual opere el Servicio. Los estudiantes serán directa y exclusivamente responsables de todas las acciones que se realicen a través de su cuenta. Asimismo, los estudiantes se comprometen a no ceder ni transferir su cuenta a terceros, a no utilizar cuentas de terceros, y en caso de que así lo hicieran, el titular de la cuenta será el responsable de toda conducta que se derive de su uso por un tercero.</p>
    <p class="reglamento__parrafo">Si un estudiante tuviera razones para creer que su cuenta ya no es segura (por ejemplo, en caso de divulgación, robo o uso no autorizado o de su nombre de estudiante, contraseña, número de tarjeta de crédito o débito, entre otros), deberá notificar inmediatamente a K’TA Institute, de esta circunstancia. Debido a su obligación de mantener su clave de acceso confidencial, el estudiante será responsable de todos los perjuicios causados a K’TA Institute, por el uso no autorizado de su clave de acceso.</p>

    <p class="reglamento__parrafo">Los estudiantes aceptan que todo contenido publicado por ellos en el Sitio Web podrá ser reproducido, distribuido, modificado, publicado, comunicado o utilizado por K’TA Institute, para cualquier propósito vinculado con los Servicios, el marketing y la publicidad del Sitio Web y/o de los Servicios, entre otros. Asimismo, K’TA Institute, se reserva el derecho, sin previo aviso, de suprimir o cancelar todo contenido publicado por los estudiantes que contravenga estos Términos y Condiciones.</p>
    <p class="reglamento__parrafo">El Sitio Web puede incluir enlaces o referencias a sitios de terceros. K’TA Institute, no se hace responsable del contenido de ningún sitio de referencia ni de la información, materiales, productos o servicios disponibles o accesibles a través de tales sitios. Cuando un estudiante ingrese a cualquiera de estos sitios, quedará sujeto a los términos y condiciones de uso de estos. K’TA Instituto no se hace responsable del contenido expresado en cualquier de los videos puestos a disposición de los estudiantes por los Tutores.</p>

    <h3 class="reglamento__subtitulo">Conductas prohibidas en el sitio</h3>
    <p class="reglamento__parrafo">Los estudiantes se comprometen a utilizar el Sitio Web y los Servicios de conformidad con la ley, la moral y buenas costumbres generalmente aceptadas, el orden público y con las disposiciones de estos Términos y Condiciones. A continuación, se detallan, a modo ejemplar, algunas conductas prohibidas en el uso del Sitio Web:</p>

    <p class="reglamento__parrafo">Utilizar el Sitio Web con un propósito ilegal o vulneratorio de cualquier ley de los Estados Unidos incluyendo, y sin limitación, las leyes que rigen la propiedad intelectual y otros derechos de propiedad, derechos de imagen, protección de datos personales y privacidad.</p>
    <p class="reglamento__parrafo">Alquilar, arrendar, vender, revender, distribuir o transferir información académica otorgada por K’TA Institute, o cualquier otro material, contenido o información que integre el Sitio Web.</p>
    <p class="reglamento__parrafo">Subir, cargar o distribuir cualquier anuncio, material o contenido difamatorio, calumnioso, inexacto, ofensivo, indecente, pornográfico, amenazante, vulgar, discriminatorio, de odio racial, étnicamente ofensivo, o generalmente inapropiado.</p>
    <p class="reglamento__parrafo">Hacerse pasar por otra persona o entidad, afirmar falsamente afiliación con cualquier persona o entidad, acceder a las claves de acceso de otros estudiantes sin su permiso, falsificar la firma ológrafa o digital de otra persona, tergiversar el origen, identidad, o contenido de la información transmitida a través del Sitio Web, o realizar cualquier otra actividad engañosa o fraudulenta.</p>
    <p class="reglamento__parrafo">Realizar ofertas no solicitadas, anuncios, propuestas, o enviar spam a otros estudiantes del Sitio Web. Esto incluye, sin estar limitado a: publicidad, material promocional, distribución de publicidad comercial, anuncios informativos, peticiones de caridad, peticiones de firmas, entre otros.</p>
    <p class="reglamento__parrafo">Suprimir, eludir, deshabilitar o interferir con funciones relacionadas con la seguridad del Sitio Web, que impidan, dificulten o limiten el uso de cualquier contenido accesible a través del Sitio Web por parte de otros estudiantes o que impongan limitaciones en el uso del Sitio Web.</p>
    <p class="reglamento__parrafo">Eliminar los anuncios, materiales, información o contenidos del Sitio Web.</p>
    <p class="reglamento__parrafo">Utilizar ingeniería inversa, descompilar, desmontar o tratar de descubrir el código fuente del Sitio Web o cualquiera de sus partes, excepto y únicamente en la medida en que dicha actividad esté expresamente permitida por la ley aplicable, a pesar de esta limitación.</p>
    <p class="reglamento__parrafo">Interferir intencionalmente con el funcionamiento del Sitio Web o con el uso por cualquier estudiante de los Servicios, por cualquier medio.</p>
    <p class="reglamento__parrafo">Mantener un trato irrespetuoso con los demás estudiantes, y los profesores (tutores)</p>
    <p class="reglamento__parrafo">Publicar, en cualquier sección del Sitio Web, comentarios que incluyan información personal de otro estudiante o tutores.</p>
    <p class="reglamento__parrafo">El uso de nombres, direcciones y números de teléfonos falsos con el propósito de engañar a otros estudiantes o tutores.</p>
    <p class="reglamento__parrafo">Tentar compartir las informaciones, imágenes, datos personales con personas, familiares y amistades que residen en países extranjeros.</p>
    <p class="reglamento__parrafo">Los estudiantes declaran y reconocen que las conductas anteriormente descritas suponen una grave violación de estos Términos y Condiciones, reservándose K’TA Institute, el derecho de suspender o cancelar y/o suspender la cuenta del estudiante infractor y de iniciar contra quien las lleve a cabo las acciones legales correspondientes. K’TA Institute, no prohíbe que los estudiantes publiquen sus propios datos personales en el Sitio Web, pero aconseja firmemente no hacerlo.</p>

    <h3 class="reglamento__subtitulo">Infracciones a los términos y condiciones</h3>

    <p class="reglamento__parrafo">K’TA Institute, se reserva el derecho de suspender o cancelar la cuenta de aquellos estudiantes que incumplan estos Términos y Condiciones, sin que ello implique derecho a indemnización alguna por parte del estudiante infractor. Asimismo, K’TA Institute, podrá, suprimir o cancelar todo contenido publicado por los estudiantes en el Sitio Web que contravenga estos Términos y Condiciones.</p>

    <h3 class="reglamento__subtitulo">Privacidad</h3>

    <p class="reglamento__parrafo">Para poder acceder a los Servicios, los estudiantes deberán registrarse en el Sitio Web, entregando toda la información requerida en el correspondiente formulario. El estudiante declara y garantiza que toda la información suministrada es completa, actual y verdadera. El estudiante autoriza expresamente a K’TA Institute, a utilizar la información entregada al momento de registrarse, en los términos descritos en la “Política de Privacidad de K’TA Institute,” disponible en este sitio, la que el estudiante declara haber leído y en este acto acepta en forma expresa.</p>
    <p class="reglamento__parrafo">En K’ta Institute, nos preocupamos por la privacidad y protección de los datos de nuestros clientes. Por lo tanto, queremos dejar en claro que nuestros Términos y Condiciones establecen de manera explícita que en ningún caso vendemos ni distribuimos los datos personales de nuestros clientes a terceros sin su consentimiento previo.</p>
    <p class="reglamento__parrafo">La recopilación de información personal se lleva a cabo exclusivamente con el propósito de gestionar el registro en nuestros cursos y proporcionar a nuestros clientes una experiencia educativa de calidad. Utilizamos los datos suministrados por nuestros clientes únicamente para fines internos, como comunicarnos con ellos, enviarles información relevante sobre nuestros cursos, promociones y eventos del Instituto.</p>
    <p class="reglamento__parrafo">Implementamos medidas de seguridad y privacidad para proteger la integridad de los datos y garantizar que solo personal autorizado tenga acceso a esta información. Además, nos comprometemos a cumplir con todas las leyes y regulaciones vigentes en materia de protección de datos y privacidad.</p>
    <p class="reglamento__parrafo">En caso de que nuestros clientes deseen recibir información adicional o promocional de terceros, solicitaremos su consentimiento explícito y les brindaremos la opción de optar por participar o no. Valoramos la transparencia y la confianza en nuestra relación con los clientes, por lo que nos esforzamos por brindarles el control sobre sus datos personales.</p>

    <h3 class="reglamento__subtitulo">Propiedad intelectual</h3>

    <p class="reglamento__parrafo">El Sitio Web es propiedad de y K’TA Institute es operado por ésta. Las interfaces visuales, gráficos, textos, logos, diseño, compilación, información, base de datos, los productos, videos educativos, contenidos, Servicios y todos los demás elementos de este Sitio Web proporcionados por K’TA Institute están protegidos por derecho de autor, patentes o marcas comerciales, según corresponda, lo que los estudiantes declaran comprender y aceptar. Con excepción de lo expresamente autorizado por K’TA Institute, los estudiantes se comprometen a no vender, distribuir, reproducir, publicar, transmitir, editar, adaptar, crear trabajos derivados de, o hacer uso no autorizado de los contenidos disponibles en el Sitio Web.</p>
    <p class="reglamento__parrafo">Algunas herramientas del Sitio Web permiten, tanto a los estudiantes como a los profesores, subir contenidos al Sitio Web (sean creados por ellos u obtenidos de fuentes externas). En este sentido los estudiantes declaran que y se comprometen a: (a) Que ningún contenido subido o compartido por ellos en el Sitio Web vulnera derechos de terceros, particularmente aquellos derechos de propiedad intelectual;</p>
    <p class="reglamento__parrafo">Los estudiantes otorgan a K’TA Institute el derecho y licencia no exclusivos para reproducir, distribuir, ofrecer, usar y comercializar el contenido publicado a través de los Servicios, directamente o a través de terceros.</p>

    <h3 class="reglamento__subtitulo">Condiciones técnicas y de conectividad</h3>

    <p class="reglamento__parrafo">A fin de acceder a los Servicios a través de la plataforma de K’TA Institute, los estudiantes aceptan que deberán contar con requisitos técnicos y de conectividad mínimos en sus equipos y/o dispositivos que permitan un correcto uso del Sitio Web y desarrollo de los Servicios, los que se encuentran disponibles en este link. K’TA Institute no será responsable por la imposibilidad de utilizar los Servicios adecuadamente por fallas en o por falta de los requisitos mínimos técnicos y de conectividad.</p>
    <p class="reglamento__parrafo">Reiteramos la información de que la plataforma no está asequible a los usuarios residentes en los países extranjeros a los EE.UU. por razones de seguridad y protección contextual y privada.</p>

    <h3 class="reglamento__subtitulo">Vigencia de los cursos y contenidos</h3>

    <p class="reglamento__parrafo">K’TA Institute se reserva el derecho a establecer la vigencia de cada uno de los contenidos y cursos que ofrece. K’TA Institute garantiza el completo acceso a los cursos que los estudiantes hayan adquirido hasta el periodo de culminación de este, el cual está indicado en la descripción de cada nivel del programa. En caso de que por alguna razón un estudiante se vea obligado a no continuar con sus clases, K’TA Institute le brindara la oportunidad de congelar, es decir, cerrar el acceso, suspender sus pagos, y reincorporarse cuando esté en condiciones. K’TA Institute no hace devoluciones de cualquier curso, taller o webinar empezado, pero permite que el estudiante se incorpore nuevamente con tan solo cancelar un fee administrativo, si dejo pasar más de tres grupos, a la inicial registrada.</p>

    <h3 class="reglamento__subtitulo">Formas y condiciones de pago</h3>

    <p class="reglamento__parrafo">K’TA Institute es una plataforma y Sitio Web que utiliza varia formas y posibilidades de pago y cancelación de sus programas de formación a través de entidades externas y autorizadas por la ley federal a recibir pagos y ofrecer condiciones de estos. K’TA Institute ofrece sistemas de pago por tarjeta de débito/crédito, depósitos directos o en efectivo. Cualquier pago debe ser hecho en dólar estadounidense (USD). K’TA Institute ofrece un pago por partes junto con la plataforma del banco PAYPAL (ver las condiciones del momento en la plataforma online de PayPal.</p>
    <p class="reglamento__parrafo">Para acceder a los Servicios, los estudiantes deberán adquirir al menos uno de los cursos, talleres o webinares (curso de impuestos individuales y/o empresas, inmigración, seguros, inglés y más) ofrecidos por K’TA Institute como programas de desarrollo y ayuda al inmigrante de habla hispana para su mejor integración en los EE.UU. que se ofrecen en la página K’TA Institute del Sitio Web. El precio del programa según lo indicado en página web.</p>

    <h3 class="reglamento__subtitulo">Responsabilidad</h3>

    <p class="reglamento__parrafo">K’TA Institute no se hace responsable de daños derivados de o relacionados con la falta de veracidad, exactitud o actualidad de la información declarada por los estudiantes o los profesores. El estudiante es responsable de los avances en sus actividades en la plataforma, asistir a sus clases online en vivo o grabaciones. El estudiante es responsable de notificar a la coordinación académica si presenta algún inconveniente para asistir a sus clases o avanzar en el contenido, debe escribir info@ktainstitute.com. El estudiante es responsable de completar el programa de acuerdo con el nivel seleccionado, no se permite hacer cambios de interrupción, solo de avance en los niveles.</p>
    <p class="reglamento__parrafo">El estudiante es responsable de mantener sus pagos al día para tener el acceso a la plataforma en su aula y buzón de estudiante. Una vez culminado el nivel del programa el estudiante, podrá disfrutar de la membresía por dos meses continuos incluidos en su membresía. El estudiante debe mantener un comportamiento respetuoso con el tutor durante las clases en vivo o escritas.</p>


</main>

<?php include_once __DIR__.'/../components/footer.php'; ?>

<?php 

    $menuVersion = filemtime('assets/js/menu.js');
    $scripts ='
        <script src="/assets/js/menu.js?v='.$menuVersion.'"></script>
    ';
?>